import os
class Configuration():
    APP_HOST='0.0.0.0'
    APP_DEBUG=True
    APP_PORT=80
    ELASTICSEARCH_SERVER_IP='172.17.0.2'
    ELASTICSEARCH_SERVER_PORT='9200'
    MF_SYNOP_INDEX='mf_synop'
    MAX_RESULTS=1000
    MAX_RESULTS_MOST_RECENT=500
